### ISSUE TITLE
Handling invalid requests that throw exception instead of simple "not approved" with a provided reason for not approved.

### ISSUE THREAD

**Issue by tulbox** [Beanstream-DRWP/beanstream-dotnet#3]
Unfortunately there doesn't appear to be any easy way of handling bad request exceptions. It appears we can just trap the Beanstream.Api.SDK.Exceptions.InvalidRequestException, but instead of the message being something that we can safely pass directly to the end user, we have to parse it for the message (e.g. BadRequest, category: 1, code: 7: {"code":7,"category":1,"message":"DECLINE","reference":null} ). 
Am I missing something really obvious here or is this API implementation missing something so basic?

In other words, do I have to assume that a) any error with reasonable information contained somewhere in it is fit for end-user consumption (invalid CVC, invalid expiry date, etc.) will always be a Beanstream.Api.SDK.Exceptions.InvalidRequestException and b) I've got to create an error message for each error code that can be found at http://support.beanstream.com/docs/response-message-codes-descriptions.htm or I've got to string parse the JSON response server-side?

I appears upon looking at it further, all exceptions inherit from BaseApiException, but an exception I would expect would be more a "Business Rule Exception" is actually an invalid request exception (an invalid CVC) so I've got no choice at this point but to catch any BaseApiException and string parse.

**Comment by tulbox** [comment]
And it looks like the code and category don't match with http://support.beanstream.com/docs/response-message-codes-descriptions.htm. 

{"code":7,"category":1,"message":"DECLINE","reference":null}

Rather, it's a unique error ID (referencing what?) and hopefully a category that actually maps properly according to the following information:

/// The 'code' is a unique error ID, an int.
/// 
/// The 'category' is one of 4 numeric values:
///   1	- The transaction was successfully processed
///       These can be successes or failures. They indicate that the message went to the bank and it returned a response. 
///       The response could be a "payment approved" or even a "declined" response, along with many others.
///       These errors should be sent to the card holder and merchant to indicate a problem with their card.
///   2	- Business rule violation
///       This is usually a problem with how your account is configured. Sometimes it could be duplicate order number errors or something
///       similar. These errors need to be worked out by the developer before the software moves to production.
///   3	- Input data problem
///       The requests are inproperly formatted or the data is wrong. Invalid card number errors (code 52) can also appear here.
///       Mopst of these errors need to be worked out by the developer before the software moves to production.
///   4	- Transaction failed due to technical problem
///       There was a problem on the Beanstream or bank servers that is out of your control. These will respond with an http status code
///       in the 500+ range. Card holders should wait a minute and try the transaction again.


Currently, I've got very rough handling via the following which pending Beanstream's response, will hopefully be *greatly* improved upon:

            catch (Beanstream.Api.SDK.Exceptions.BaseApiException ex)
            {
                Logger.Error(ex);
                //_mailer.PaymentFailed(model);
                var acceptableToShow = ex.Code == 1;
                if (acceptableToShow)
                {
                    ErrorWithContact("Sorry, your payment request has been declined. Please double-check your payment details and try again.<br /><br />" + ex.Response);
                }
                else
                {
                    ErrorWithContact("Sorry, but there has been an error processing your request. The administrator has been notified. Please refresh the page and try again.");
                }
            }

**Comment by tulbox** [comment]
A good example of how this should be handled can be found at https://stripe.com/docs/api#errors.

            catch (StripeException ex)
            {
                // There was a problem with the order on Stripe's end. Safe to show actual exception message (i.e. "CVC is wrong"). See https://stripe.com/docs/api#errors for potential errors.
                Logger.Error(ex);
                //model.FailureReason = ex.Message;
                //_formMailer.PaymentFailedClassifiedAd(model).SendAsync();
                ErrorWithContact(ex.Message);
            }

**Comment by BeanstreamDeveloper** [comment]
Thanks for the feedback tulbox. We greatly appreciate it. The SDK is always evolving and changing and as more users integrate with it we will add their changes and suggestions. Error messages is one that is always a little tricky with credit cards. You do not want to send specific error messages to the users in case they are using your merchant service to test purchased card numbers to see what ones are valid and what ones aren't. In general you want to show the user a generic error message if a card is declined.

I've created a ticket for our tech writer so the error codes will be updated and I will improve the code samples as well as add some clarity to the code for handling exceptions.

Thanks again

**Comment by tulbox** [comment]
Thanks for the response. I have a couple questions/concerns with your response:

1. Your current API does not make it easy (because of lack of, or inaccurate/outdated, documentation for one) to easily help the end user figure out if it's an error on their part, or whether it was declined because an actual problem with their card. You state that this is problematic because of misuse of the merchant service, but Stripe has no problem providing more specific information. Or rather, the items that can be exposed, they make it dead easy: if it's a "StripeException", you don't need to worry about error codes or anything: you can just spit out the message and be done (even if said message is simply "Payment has been declined").

2. Documentation states that approval status should be checked for response.Approved == "1". For one thing, I've yet to have seen it come out as anything but == "1" because every error/decline just throws an exception, and two, why ever, when it's an API, would you not set response.Approved to be a bool? It's either approved or not. Anything that reduces the friction of needing to look to documentation and wondering if it's actually correct is the mark of a good API.

3. So you're saying (please verify this) I need to do the following currently:

a) Check for response.Approved == "1", and...
b) Catch any BaseApiException:

              catch (Beanstream.Api.SDK.Exceptions.BaseApiException ex)
              {
                  _logger.Error(ex);
                  //_mailer.PaymentFailed(model);
                 // Category 1: successfully processed, but could be declined (at which point it throws an exception instead of just setting reasponse.Approved != 1.).
                 // Category 2: business rule violation: usually problem with how account is configured. Could also be duplicate order number.
                 // Category 3: input data problem. E.g. incorrect CVC (e.g. 3 digits instead of 4 for Amex).
                // Cateogry 4: technical problem out of our control. Card holders should wait a minute and try again.

                var declined = ex.Category == 1 || ex.Category == 3;
                var waitAMinute = ex.Category == 4;
                if (declined)
                {
                    ErrorWithContact(
                        "Payment Declined",
                        "Sorry, your payment request has been declined. Please double-check your payment details and try again.");
                }
                else if (waitAMinute)
                {
                    ErrorWithContact(
                        "Payment Processor Unavailable",
                        "Unfortunately, merchant services are currently unavailable. Please wait a few minutes and try again.");
                }
                else
                {
                    ErrorWithContact(
                        "Error",
                        "Sorry, but there has been an error processing your request. The administrator has been notified. Please refresh the page and try again.");
                }
            }

Why could these not be simply be different exception types with sanitized exception.Message that can just be presented to the end user? Or better yet, just one exception. Instead, I'm left pouring through the Legato source as well as your C# API source to find out what exactly I need to catch and what exactly I can present to the end user. Then after trial and error refining further. Wouldn't this be what you'd want to present instead:

            catch (Beanstream.Api.SDK.Exceptions.BeanstreamException ex)
            {
                _logger.Error(ex);
               // Mechanism to notify user with ex.Message (which is safe to present to user)
             }

**Comment by BeanstreamDeveloper** [comment]
Hi tulbox,

It is up to stripe to determine how much error information needs to be returned. We have been in the industry for a long time and have learned that revealing very specific errors to card holders has caused problems for merchants in the past. Thus we prefer more generic error message for the card holders. That being said it needs to be easier for a developer to know what messages should be shown to the end user.

We just added the following to the SDK BaseApiException class:
  public string UserFacingMessage () // specific error message if IsUserError() is true or a generic error message if IsUserError() is false. This message can be forwarded to the card holder for all exceptions.
  public bool IsUserError() // if a message should be shown to the user or was caused by user input. False will signal that the error was not caused by the user.

You will only need to catch a BaseApiException and display ex.UserFacingMessage() to the card holder. IsUserError() can be used for more fine grained control if needed and to track down errors during implementation.

A check for Approved() is not necessary and is just a mapping to the response data. The c# SDK communicates using our REST API which will only return a 200 OK http status code iff the request was approved. Our other APIs (Soap and Querystring) would return a 200 OK but also state whether the request was approved or now. We will update the documentation and code samples to clarify this, I will also protect the Approved() method.

The changes to the documentation are still in the works but should be completed soon.

Thanks  again for the feedback.

**Comment by tulbox** [comment]
Thanks for taking our suggestions and running with them. Could you notify when the Nuget package has been updated with the latest changes?

**Comment by BeanstreamDeveloper** [comment]
I just pushed up version 1.0.0-rc2 to nuget gallery. If you run into any issues let me know. I can also give you commit access if you find anything that needs tweaking to improve usability.

Cheers

**Comment by adityasrivastava** [comment]
Your Member Account > Process Transaction > Batch Processing > Payment Profile API..the code referred to Invalid Passcode.

https://support.na.bambora.com/bic/w/index.html#docs/payment-profiles-api-customer-response-codes.htm?Highlight=code

**Comment by tulbox** [comment]
Since our previous implementation was a) working and confirmed functionally correct and b) it was in production and I didn't want to waste any more time on it, years later I'm only now looking at updating. Lo and behold, the only implementation that was done was the following:

```
		/**
		 * If this exception was cause by user input ie. invalid card number or declines.
		 * Returns false for all other errors that were not caused by user input, such
		 * as network timeouts, message formatting, etc.
		 */
		public bool IsUserError() {
			return false;
		}

		/**
		 * Most exceptions should not be shown in detail to the user. Only some API exception
		 * sublcasses will provide detailed error messages. If you so decide to display the error
		 * message details, you can call exception.Message().
		 */
		public string UserFacingMessage ()
		{
			return "There was an error processing your request. Please try again or use a different card.";
                 }
```

IsUserError() always returns false and UserFacingMessage() always returns a generic message. This is obviously worse than useless since it pretends to be useful, but is only one more useless rabbit trail to go down. Back to my lovely spaghetti mess of checks already implemented.
