### ISSUE TITLE
Adding a new Credit Card using token is missing when using Profiles API

### ISSUE THREAD

**Issue by tutkoo** [Beanstream-DRWP/beanstream-dotnet#4]
It would make lot of sense, if a new Credit card can be added to Customer Profile using a token instead of providing the whole credit card. As of now adding new Credit card requires sending the complete card information; this will increase the security risk and hence using tokens will help reduce that risk.

**Comment by BeanstreamDeveloper** [comment]
This can be done, it is just not explicitly defined in the SDK. I will add it right away.

**Comment by BeanstreamDeveloper** [comment]
Change has been committed to [04fc748](https://github.com/Beanstream-DRWP/beanstream-dotnet/commit/04fc7487dd969efea944d045abd3aa9591ae9a46)

**Comment by tutkoo** [comment]
Thank you very much for amazingly quick turn around.
