### ISSUE TITLE
beanstream.Payments.PreAuth doesn't accept ProfilePaymentRequest

### ISSUE THREAD

**Issue by tutkoo** [Beanstream-DRWP/beanstream-dotnet#5]
This is documented in one of the examples that you can pass profile object to create a pre-authorized payment; but seems to be missing in the latest C# SDK.

You can only provide Token or CardPaymentRequest.

**Comment by BeanstreamDeveloper** [comment]
A profile can be used but it is missing from the SDK. I will add this in right now and push out a new release.
Thanks for finding the issue.

**Comment by BeanstreamDeveloper** [comment]
Change has been committed to [04fc748](https://github.com/Beanstream-DRWP/beanstream-dotnet/commit/04fc7487dd969efea944d045abd3aa9591ae9a46)

**Comment by tutkoo** [comment]
Thank you very much for amazingly quick turn around.

**Comment by BeanstreamDeveloper** [comment]
No problem. Let me know if you run into any issues. I will push out a new release of the SDK to NuGet Gallery today.
